version: '3'
services:
  app:
    build: ./mydjango
    command: bash -c "uwsgi --ini uwsgi.ini"
    volumes:
      - ./mydjango:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: mysql/mysql-server
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=demodb
      - MYSQL_ROOT_PASSWORD=123456

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      # - ./mydjango/static/:/usr/share/nginx/html/static/:ro
      - ./my-app/build:/usr/share/nginx/html
    #  - ./my-app/build/static:/usr/share/nginx/html/static:ro
    links:
      - app
    depends_on:
      - app
    restart: always
