version: '3.6'
services:
  app:
    restart: always
    build: .
    command: bash -c "uwsgi --ini uwsgi.ini"
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      -db

  db:
    image: mysql:5.7
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restsrt: always
    environment:
      - MYSQL_DATABASE=demodb
      - MYSQL_ROOT_PASSWORD=123456

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      -./static:/usr/share/nginx/html/static:ro
      - ./build:/usr/share/nginx/html
    links:
      - app
    depends_on:
      - app
    restart: always
