# Generated by Django 3.2.4 on 2021-07-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify_name', models.CharField(blank=True, max_length=50, null=True)),
                ('classify_tag', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['classify_name'],
            },
        ),
        migrations.CreateModel(
            name='Movieapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=225, null=True)),
                ('image_paths', models.CharField(blank=True, max_length=225, null=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('hd', models.CharField(blank=True, max_length=25, null=True)),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=25, null=True)),
                ('actors', models.CharField(blank=True, max_length=225, null=True)),
                ('serialize', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('release_time', models.CharField(blank=True, max_length=25, null=True)),
                ('update_time', models.CharField(blank=True, max_length=25, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('classification', models.ManyToManyField(to='myapp.Classification')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoYun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(blank=True, max_length=225, null=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieofvideoyun', to='myapp.movieapi')),
            ],
            options={
                'ordering': ['video_url'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(blank=True, max_length=225, null=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieofvideo', to='myapp.movieapi')),
            ],
            options={
                'ordering': ['video_url'],
            },
        ),
    ]
